### ISSUE TITLE
AFAICT, East/West and South/Midwest Final Fours are wrong

### ISSUE THREAD

**Issue by bpollack** [listrophy/lazy_ncaa_elm#2]
I love the idea, but it seems as if the brackets used here don't actually match the official brackets. Notably, the real brackets have East/West and South/Midwest Final Four games, making combos like Duke and Gonzaga for the final impossible, but your groupings instead have a West/South and East/Midwest matchup, which allows that.

**Comment by listrophy** [comment]
Fixed it last year.... stayed fixed for this year! :)

**Comment by listrophy** [comment]
Thanks for pointing this out, btw. (and sorry for the extra email)
